# Generated by Django 2.2.4 on 2019-09-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_kashano', models.CharField(blank=True, max_length=500, null=True)),
                ('transactions_kashano', models.CharField(blank=True, max_length=500, null=True)),
                ('estates_kashano', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('data_id', models.IntegerField(null=True)),
                ('estate_type_id', models.CharField(blank=True, max_length=100, null=True)),
                ('installation', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('land_area', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('front_length', models.CharField(blank=True, max_length=100, null=True)),
                ('direction', models.CharField(blank=True, max_length=100, null=True)),
                ('rooms_count', models.CharField(blank=True, max_length=100, null=True)),
                ('floors_count', models.CharField(blank=True, max_length=100, null=True)),
                ('units_count', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('total_units_count', models.CharField(blank=True, max_length=100, null=True)),
                ('cover', models.CharField(blank=True, max_length=100, null=True)),
                ('frontage', models.CharField(blank=True, max_length=100, null=True)),
                ('wc', models.CharField(blank=True, max_length=100, null=True)),
                ('kitchen', models.CharField(blank=True, max_length=100, null=True)),
                ('document', models.CharField(blank=True, max_length=100, null=True)),
                ('has_building', models.CharField(blank=True, max_length=100, null=True)),
                ('habitation', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('map', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('fronts_count', models.CharField(blank=True, max_length=100, null=True)),
                ('lines_count', models.CharField(blank=True, max_length=100, null=True)),
                ('has_modify', models.CharField(blank=True, max_length=100, null=True)),
                ('allocation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('has_manufacturing_license', models.CharField(blank=True, max_length=100, null=True)),
                ('has_wall', models.CharField(blank=True, max_length=100, null=True)),
                ('has_landscaping', models.CharField(blank=True, max_length=100, null=True)),
                ('vegetation', models.CharField(blank=True, max_length=100, null=True)),
                ('car_way', models.CharField(blank=True, max_length=100, null=True)),
                ('urban_position', models.CharField(blank=True, max_length=100, null=True)),
                ('is_habitable', models.CharField(blank=True, max_length=100, null=True)),
                ('has_agricultural_water', models.CharField(blank=True, max_length=100, null=True)),
                ('has_endofwork', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_from_asphalt', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment', models.ManyToManyField(to='one.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reject_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('settlement_sale_price', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_price', models.CharField(blank=True, max_length=100, null=True)),
                ('settlement_rent_price', models.CharField(blank=True, max_length=100, null=True)),
                ('mortgage_only', models.CharField(blank=True, max_length=100, null=True)),
                ('mortgage_price', models.CharField(blank=True, max_length=100, null=True)),
                ('rent_price', models.CharField(blank=True, max_length=100, null=True)),
                ('sale_situation', models.CharField(blank=True, max_length=100, null=True)),
                ('has_loan', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('is_special', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('expired_at', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('visit', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True)),
                ('estate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='one.Estate')),
            ],
        ),
    ]
