# Generated by Django 2.2.4 on 2019-09-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estate',
            old_name='equipment',
            new_name='equipments',
        ),
    ]
