# Generated by Django 2.2.4 on 2019-09-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_auto_20190904_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
