# Generated by Django 2.2.4 on 2019-09-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_equipment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
