# Generated by Django 2.2.4 on 2019-09-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_auto_20190906_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
