# Generated by Django 2.2.4 on 2019-09-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_auto_20190908_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
