# Generated by Django 2.2.5 on 2019-09-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_setting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
