# Generated by Django 2.2.5 on 2019-09-30 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kashano', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='download_time',
        ),
    ]
