# Generated by Django 2.2.5 on 2019-09-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kashano', '0002_remove_estate_download_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='download_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
