# Generated by Django 2.2.5 on 2019-09-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kashano', '0003_estate_download_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='download_status',
            field=models.BooleanField(default=False),
        ),
    ]
