# Generated by Django 2.2.5 on 2019-09-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kashano', '0004_auto_20190930_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('cookie', models.CharField(blank=True, max_length=500, null=True)),
                ('transactions', models.CharField(blank=True, max_length=500, null=True)),
                ('estates', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
