# Generated by Django 2.2.5 on 2019-09-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kashano', '0006_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
