# Generated by Django 2.2.5 on 2019-09-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kashano', '0007_auto_20190930_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
