# Generated by Django 2.2.4 on 2019-10-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kashano', '0008_auto_20190930_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='delete_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
