# Generated by Django 2.2.5 on 2019-10-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kashano', '0009_auto_20191007_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='download_time',
        ),
        migrations.AlterField(
            model_name='estate',
            name='download_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
